In [1]:
class Employee:
    num_employees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.num_employees += 1

    @staticmethod
    def average_salary(employees):
        total_salary = sum(emp.salary for emp in employees)
        return total_salary / len(employees)

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, experience):
        super().__init__(name, family, salary, department)
        self.experience = experience

employee1 = Employee("John Doe", "Family A", 60000, "HR")
employee2 = Employee("Jane Smith", "Family B", 75000, "Finance")

fulltime_employee1 = FulltimeEmployee("Alice Johnson", "Family C", 80000, "IT", 3)
fulltime_employee2 = FulltimeEmployee("Bob Williams", "Family D", 90000, "Engineering", 5)

employees = [employee1, employee2, fulltime_employee1, fulltime_employee2]
avg_salary = Employee.average_salary(employees)

print("Total number of employees:", Employee.num_employees)
print("Average salary:", avg_salary)

Total number of employees: 4
Average salary: 76250.0


In [2]:
import numpy as np
random_vector = np.random.uniform(1, 20, size=20)
print("Original array:")
print(random_vector)

reshaped_array = random_vector.reshape(4, 5)

max_indices = np.argmax(reshaped_array, axis=1)

reshaped_array[np.arange(4), max_indices] = 0

print("\nReshaped array:")
print(reshaped_array)

Original array:
[12.21239718  2.16240881  3.15838817  8.62167811  6.12389539 16.10806443
 11.42459601 18.76059084 13.16142029 17.00069625 19.38456398  4.93136608
 16.28820078 17.21109435  7.67058427 12.95952217 17.2150565  13.29886347
 16.75958444  6.18644663]

Reshaped array:
[[ 0.          2.16240881  3.15838817  8.62167811  6.12389539]
 [16.10806443 11.42459601  0.         13.16142029 17.00069625]
 [ 0.          4.93136608 16.28820078 17.21109435  7.67058427]
 [12.95952217  0.         13.29886347 16.75958444  6.18644663]]
